#!/usr/bin/env bash
# Idempotent Cloud Agent setup for Exeora. Runs after the repository is checked
# out. Node 22 (nvm) and the pinned Rust toolchain come from the base image;
# this script adds Bun, installs JS dependencies, writes local gateway secrets,
# builds the site the Worker serves, and warms the CLI build.
set -euo pipefail

# Bun is the repository's package manager (see package.json / CONTRIBUTING.md)
# but is not in the base image. Install it once, then expose it on a system PATH
# entry so non-interactive install/start/terminal shells find it too.
if ! command -v bun >/dev/null 2>&1 && [ ! -x "$HOME/.bun/bin/bun" ]; then
  curl -fsSL https://bun.sh/install | bash
fi
export PATH="$HOME/.bun/bin:$PATH"
if [ -x "$HOME/.bun/bin/bun" ] && [ ! -e /usr/local/bin/bun ] && command -v sudo >/dev/null 2>&1; then
  sudo ln -sf "$HOME/.bun/bin/bun" /usr/local/bin/bun || true
fi

# JS dependencies for every workspace (packages/* and apps/*).
bun install --frozen-lockfile

# Local gateway secrets, git-ignored. The OAuth client ids/secrets are
# placeholders: they unblock the workerd test suite and let the sign-in page
# render, but real GitHub/Google sign-in needs real OAuth apps. The two signing
# secrets are generated fresh (>=32 bytes, or the codec refuses to start). An
# existing file is left untouched so real credentials are never clobbered.
DEV_VARS="apps/gateway/.dev.vars"
if [ ! -f "$DEV_VARS" ]; then
  {
    echo "# Local development secrets (git-ignored), generated by .cursor/install.sh."
    # Points the OAuth issuer at the local dev server; not sensitive.
    echo "EXEORA_BASE_URL=http://localhost:8787" # pragma: allowlist secret
    cat <<EOF
GITHUB_CLIENT_ID=dev-github-client-id
GITHUB_CLIENT_SECRET=dev-github-client-secret
GOOGLE_CLIENT_ID=dev-google-client-id
GOOGLE_CLIENT_SECRET=dev-google-client-secret
COOKIE_SECRET=$(openssl rand -hex 32)
REQUEST_STATE_SECRET=$(openssl rand -hex 32)
EOF
  } > "$DEV_VARS"
fi

# The gateway Worker serves the built landing + dashboard through its ASSETS
# binding, and the asset tests read the real files, so build before anything
# runs them (and before `bun run test`).
bun run --cwd apps/web build

# Warm the Rust build so the `exeora` CLI is ready to run and test without a
# cold compile on first use.
cargo build -p exeora-cli
