[package]
name = "exeora-protocol-gen"
description = "Generate checked-in Rust protocol types from Exeora JSON Schema"
publish = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.100"
serde_json = "1.0.145"
typify = "0.7.0"
schemars = "1.2.2"
prettyplease = "0.3.0"
syn = { version = "3.0.3", features = ["full"] }
