/**
 * Draws every file the brand kit hands out, plus the favicon.
 *
 * Run it with `bun run brand` after changing the mark, the wordmark or the
 * palette. The output is committed: this is not part of the build, because the
 * site should not need a rasteriser to deploy.
 *
 * Everything traces back to two sources. The tiles come from
 * `@exeora/design/mark`, the colours from `@exeora/design/tokens`, and the
 * lockup from `packages/design/wordmark.svg`, whose letters are already
 * outlines. Nothing here restates a number that lives somewhere else.
 */

import { mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  BRAND_GROUPS,
  brandFiles,
  KIT_FILENAME,
  PURE_BLACK,
  PURE_WHITE,
} from "@exeora/design/brand";
import { MARK_SQUARE_RADIUS, MARK_TILE, markSvg } from "@exeora/design/mark";
import { readTokens, token } from "@exeora/design/tokens";
import { Resvg } from "@resvg/resvg-js";
import { zipSync } from "fflate";

const BRAND_DIR = "apps/web/landing/public/brand";
const FAVICON = "apps/web/landing/public/favicon.svg";
const DATA = "packages/design/brand-data.json";

const light = token("--color-foreground");
const dark = token("--color-bg");

const wordmarkSource = readFileSync("packages/design/wordmark.svg", "utf8");

/** The lockup, recoloured. `currentColor` is the only thing that varies. */
function wordmarkSvg(fill: string): string {
  return wordmarkSource.replace('fill="currentColor"', `fill="${fill}"`);
}

const written: string[] = [];

function write(name: string, contents: string | Uint8Array): void {
  writeFileSync(join(BRAND_DIR, name), contents);
  written.push(name);
}

/**
 * Rasterise at a fixed width. Every source here is square or has a fixed
 * aspect, so width alone pins the output down, and resvg leaves whatever the
 * SVG does not paint transparent.
 */
function png(svg: string, width: number): Buffer {
  return new Resvg(svg, { fitTo: { mode: "width", value: width } }).render().asPng();
}

rmSync(BRAND_DIR, { recursive: true, force: true });
mkdirSync(BRAND_DIR, { recursive: true });

// The two that inherit their colour, for embedding rather than downloading.
write("exeora-mark.svg", markSvg({ title: "Exeora" }));
write("exeora-wordmark.svg", wordmarkSource);

// --- The mark -------------------------------------------------------------

const markVariants = {
  "mark-light": markSvg({ fill: light, square: true, title: "Exeora" }),
  "mark-dark": markSvg({ fill: dark, square: true, title: "Exeora" }),
  "mark-on-brand": markSvg({ fill: light, background: dark, title: "Exeora" }),
  // Full bleed and absolute values: the point of this one is to satisfy a
  // listing that says "black background, white logo" literally.
  "mark-on-black": markSvg({
    fill: PURE_WHITE,
    background: PURE_BLACK,
    backgroundRadius: 0,
    title: "Exeora",
  }),
} as const;

const wordmarkVariants = {
  "wordmark-light": wordmarkSvg(light),
  "wordmark-dark": wordmarkSvg(dark),
} as const;

const sources: Record<string, string> = { ...markVariants, ...wordmarkVariants };

for (const group of BRAND_GROUPS) {
  for (const variant of group.variants) {
    const svg = sources[variant.id];
    if (!svg) throw new Error(`No source for brand variant ${variant.id}`);

    if (variant.svg) write(variant.svg, svg);
    for (const size of variant.pngSizes) write(variant.png(size), png(svg, size));
  }
}

// --- The favicon ----------------------------------------------------------

writeFileSync(
  FAVICON,
  markSvg({ fill: light, background: dark, title: "Exeora" }).replace(
    "\n  <rect",
    `\n  <!-- Generated by scripts/brand-assets.ts from packages/design/mark.ts.
       Run \`bun run brand\` rather than editing this. -->\n  <rect`,
  ),
);

// --- The kit --------------------------------------------------------------

const readme = `Exeora brand assets
===================

${brandFiles().length} files, drawn from one definition of the mark. The latest
set is always at https://exeora.dev/brand/.

Files
-----

exeora-mark*        The three tiles on their own.
exeora-wordmark*    The tiles plus the name, locked up.

  *-light           For dark backgrounds. ${light}.
  *-dark            For light backgrounds. ${dark}.
  *-on-brand        The tiles on the brand square, rounded. For icon slots.
  *-on-black        ${PURE_WHITE} on ${PURE_BLACK}, full bleed, for listings
                    that ask for exactly that.

  exeora-mark.svg and exeora-wordmark.svg carry currentColor instead of a
  colour, for embedding in something that sets its own.

Using them
----------

Keep clear space of at least the width of one tile on every side. Do not
recolour, rotate, stretch, outline, add effects to, or box in the mark, and do
not rebuild the wordmark by setting the name in another face.

Licence
-------

Exeora's source is AGPL-3.0-only. The name and the mark are not: they are
Exeora's, and this kit is permission to use them to refer to Exeora, in
editorial writing, integration listings and documentation. It is not permission
to suggest Exeora endorses or is affiliated with anything.

Inter and JetBrains Mono are licensed under the SIL Open Font License 1.1 and
are not included here.

Questions: hello@exeora.dev
`;

const entries: Record<string, Uint8Array> = { "readme.txt": Buffer.from(readme, "utf8") };
for (const name of written) {
  entries[name] = new Uint8Array(readFileSync(join(BRAND_DIR, name)));
}

// A fixed timestamp, so rerunning without a change produces the same bytes and
// does not show up as a diff. It has to be a Date object, and one comfortably
// inside 1980-2099 in every timezone, because fflate reads the year locally.
write(KIT_FILENAME, zipSync(entries, { level: 9, mtime: new Date("2000-01-01T12:00:00Z") }));

// --- What the page needs --------------------------------------------------

// The brand page quotes file sizes and paints swatches, and it can do neither
// from the filesystem: a bundled page has no cwd it can trust and no
// `import.meta.url` that survives. So the facts are written out here, from the
// same run that produced the files and read the same tokens.css.
writeFileSync(
  DATA,
  `${JSON.stringify(
    {
      sizes: Object.fromEntries(
        written.map((name) => [name, statSync(join(BRAND_DIR, name)).size]),
      ),
      tokens: Object.fromEntries(readTokens()),
    },
    null,
    2,
  )}\n`,
);

const clearSpace = MARK_TILE;
console.log(
  `${written.length} files in ${BRAND_DIR} (clear space: ${clearSpace}/64 of the mark's width, corner radius ${MARK_SQUARE_RADIUS}/64)`,
);
